<?php require_once("header.php"); ?>

<div class="counsel-content-wrapper"><div class="counsel-content counsel-page">
	<header id="page-title" class="page-title-wrap"><div class="page-title-wrap-inner" data-property="no-video"> <span class="page-title-overlay"></span>
	<div class="container"><div class="row"><div class="col-md-12"><div class="page-title-inner"><div class="pull-center">
		<h1 class="page-title">Contact Us</h1><div id="breadcrumb" class="breadcrumb"><a href="">Home</a> <span class="current">Contact Us</span>
	</div></div></div></div></div></div></div></header><div class="counsel-content-inner"><div class="container"><div class="row">
		<div class="col-md-12"><div id="primary" class="content-area clearfix"><div id="page-468" class="post-468 page type-page status-publish hentry">
			<div class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-4"><div class="vc_column-inner">
				<div class="wpb_wrapper"><div class="vc_empty_space"   style="height: 74px"><span class="vc_empty_space_inner"></span></div>
				<div class="section-title-wrapper shortcode-rand-7 counsel-inline-css" data-css="&quot;.shortcode-rand-7 .section-title { text-transform: none; }&quot;">
					<div class="title-wrap"><h3 class="section-title">Address</h3></div><div class="section-description"><strong>Address:</strong> P.O. Box 1111 Nairobi , Nairobi - Kenya</p><p><strong>Phone:</strong> +254702344321</p><p><strong>Email:</strong> <a href="mailto:info@ramcateleservices.co.ke">info@ramcateleservices.co.ke</a></p><p><strong>Website:</strong> <a href="https://ramca.com/">https://ramca.com/ </a>
				</div></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-1"><div class="vc_column-inner"><div class="wpb_wrapper"></div>
			</div></div><div class="wpb_column vc_column_container vc_col-sm-7"><div class="vc_column-inner"><div class="wpb_wrapper">
				<div class="wpb_gmaps_widget wpb_content_element"><div class="wpb_wrapper"><div class="wpb_map_wraper">
					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6304.829986131271!2d-122.4746968033092!3d37.80374752160443!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808586e6302615a1%3A0x86bd130251757c00!2sStorey+Ave%2C+San+Francisco%2C+CA+94129!5e0!3m2!1sen!2sus!4v1435826432051" width="665" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
					</div></div></div></div></div></div></div><div class="vc_row wpb_row vc_row-fluid vc_custom_1535467663151">
						<div class="wpb_column vc_column_container vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"></div></div></div><div class="wpb_column vc_column_container vc_col-sm-8"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="section-title-wrapper text-center shortcode-rand-9 counsel-inline-css" data-css="&quot;.shortcode-rand-9 .section-title { text-transform: none; }&quot;"><div class="title-wrap"><h3 class="section-title">Drop us a Link</h3></div><div class="section-description"></div></div><div class="contact-form-wrapper contact-form-classic text-center" data-css="&quot;&quot;"><div class="contact-form"><div role="form" class="wpcf7" id="wpcf7-f7-p468-o2" lang="en-US" dir="ltr"><div class="screen-reader-response"></div><form action="/counsell/contact-us/#wpcf7-f7-p468-o2" method="post" class="wpcf7-form" novalidate="novalidate"><div style="display: none;"> <input type="hidden" name="_wpcf7" value="7" /> <input type="hidden" name="_wpcf7_version" value="5.1.7" /> <input type="hidden" name="_wpcf7_locale" value="en_US" /> <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f7-p468-o2" /> <input type="hidden" name="_wpcf7_container_post" value="468" /></div><div class="row"><div class="col-md-6"> <span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="Name" /></span></div><div class="col-md-6"> <span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false" placeholder="Email" /></span></div></div><div class="row"><div class="col-md-12"> <span class="wpcf7-form-control-wrap your-subject"><input type="text" name="your-subject" value="" size="40" class="wpcf7-form-control wpcf7-text" aria-invalid="false" placeholder="Subject" /></span></div></div><div class="row"><div class="col-md-12"> <span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea" aria-invalid="false" placeholder="Message"></textarea></span></div></div><p><input type="submit" value="Submit Now" class="wpcf7-form-control wpcf7-submit" /></p><div class="wpcf7-response-output wpcf7-display-none"></div></form></div></div></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"></div></div></div></div></div></div></div></div></div></div></div></div>

	<?php require_once("footer.php"); ?>